version: 0.2

phases:
  install:
    commands:
      # none
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore CICDAWS.sln
  build:
    commands:
      - echo Build started on `date`
      - dotnet --list-sdks
      - dotnet build CICDAWS.sln --configuration Release
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Publish started on `date`
      - dotnet publish CICDAWS.sln --configuration Release --output ./publish
      - echo Copying files to the artifacts directory
      - cp -r ./publish $CODEBUILD_SRC_DIR/artifacts 
      - echo Publish completed on `date`

artifacts:
  files:
    - '**/*' 
  discard-paths: yes
  base-directory: 'artifacts' 

