version: 0.2

phases:
  install:
    commands:
      # Any installation commands here
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore CICDAWS.sln
  build:
    commands:
      - echo Build started on `date`
      - dotnet --list-sdks
      - dotnet build CICDAWS.sln --configuration Release
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Publish started on `date`
      - dotnet publish CICDAWS.sln --configuration Release --output ./publish
      - echo Copying files to the artifacts directory
      - cp -r ./publish $CODEBUILD_SRC_DIR/artifacts 
      - echo Publish completed on `date`

artifacts:
  files:
    - '**/*' # This includes all files in the specified 'base-directory'
  discard-paths: yes
  base-directory: 'artifacts' # Ensure this matches the directory where files are being copied

# Uncomment the following when the S3 bucket details are to be used:
# artifact-bucket:
#   name: 'your-s3-bucket-name'
#   packaging: 'zip'
#   path: 'devbuilds' # Use the 'devbuilds' directory inside your S3 bucket for the artifacts
#   namespace-type: 'BUILD_ID'

# cache:
#   paths:
#     - '/root/.nuget/packages/**/*'
